### PR TITLE
[FEATURE] Add additionalInfo parameter

### PR DESCRIPTION
**Pull request by vhpoet**

### CODE REVIEW

**Comment by justmoon** [comment]
Some background: This feature is to enable somebody using five-bells-sender to be able to add additional metadata to the payment. This data can be used as part of higher-level protocols being routed over ILP.

**Comment by sentientwaffle** [comment]
LGTM

**Comment by vhpoet** [comment]
@emschwartz changed to not use lodash. _Added lodash thinking it's gonna be used at some point anyway._

**Comment by emschwartz** [comment]
:) I know that thought well

**Pull request merged**
