### PR TITLE
[FEATURE] Send transfers in the memo

### PR DESCRIPTION
**Pull request by sentientwaffle**
Depends on https://github.com/interledger/five-bells-connector/pull/109

Spec/background: https://docs.google.com/document/d/1zTLQLBx0p6-Ds9Ki8nCaVBdXUK4mbJZDQOaz83n6VY8/edit

/cc @justmoon

### CODE REVIEW

**Comment by sentientwaffle** [comment]
I agree that the timeout is terrible. It wasn't needed before because by putting the payments in sequence we would automatically know that the last transfer was prepared.

It is needed now because we only PUT the first transfer. Since the sender doesn't have a server running we can't get notified when the last transfer is prepared. If the sender isn't posting the fulfillment then that path isn't used at all.

**Comment by justmoon** [comment]
Ok, since the sender posting the fulfillment is going to be removed once we have implemented recipient-acknowledged payments (like RC flow, like f-b-wallet flow) across the board, I'm ok with this hack for now. But please turn the magic numbers into named constants at least.

**Comment by sentientwaffle** [comment]
Ok

**Comment by emschwartz** [comment]
LGTM

**Pull request merged**
