### PR TITLE
[FEATURE] Payment template

### PR DESCRIPTION
**Pull request by sentientwaffle**
Requires https://github.com/interledger/five-bells-pathfind/pull/20

### CODE REVIEW

**Comment by justmoon** [comment]
Don't merge this yet please, needs to be updated for security. (Sender should always set the destination_account itself, not trust the connector..)

**Comment by sentientwaffle** [comment]
According to https://github.com/interledger/five-bells-connector/issues/50#issuecomment-172150188 there isn't a security issue here, so as soon as the Atomic Mode branch (the base) and https://github.com/interledger/five-bells-pathfind/pull/20 are ready, is this good to merge as well?

**Comment by emschwartz** [comment]
https://github.com/interledger/five-bells-connector/issues/50#issuecomment-172927651

**Comment by emschwartz** [comment]
@justmoon ready to merge this?

**Comment by justmoon** [comment]
Yeah, I think this is good to go.

**Pull request merged**
