### PR TITLE
[BREAKING] move pathfinder to connector

### PR DESCRIPTION
**Pull request by sentientwaffle**
Depends on https://github.com/interledger/five-bells-pathfind/pull/25

### CODE REVIEW

**Comment by emschwartz** [comment]
LGTM aside from the integration tests failing

**Comment by sentientwaffle** [comment]
Everything will pass once pathfinder is merged+bumped & I update the package.json to use it.

**Comment by clark800** [comment]
I'm confused; why does this depend on a five-bells-pathfind pull request if it is not requiring it? Also, what is the breaking change?

**Comment by sentientwaffle** [comment]
Oops, the comment about depending on pathfinder was meant to be for the connector PR.

Re: breaking change: the external API doesn't change, but it depends on a different connector quoting API. In my mind that counts as breaking, but I could see it either way.

**Pull request merged**
