### PR TITLE
Expose condition logic in sender (RILP-304)

### PR DESCRIPTION
**Pull request by MatthewPhinney**
We had a request from the RC team to expose the condition logic. See [this](https://ripplelabs.atlassian.net/browse/RILP-304) ticket. From my initial conversations, I got the sense that all the required functionality exists, but the sender API doesn't quite fit RC's use case. @gip @mwshortt let's discuss if we want to expose this API in `index.js` (as implemented), and also determine if any further changes are needed for RC.

### CODE REVIEW

**Comment by mwshortt** [comment]
This is great but not complete for what RC needs. getReceiptCondition, https://github.com/interledger/five-bells-sender/blob/master/src/conditionUtils.js#L13, needs to change to not assume that the receipt condition will be based on the finalTransfer. RC needs to create a receipt condition that will be based on and signed by the receiving RC. Does that make sense?

**Comment by gip** [comment]
```js
function getReceiptCondition (finalTransfer, state) {
  // Execution condition is the final transfer in the chain
  return getTransferState(finalTransfer)
    .then(finalTransferState => ({
      message_hash: hashJSON({
        id: finalTransfer.id,
        state: state
      }),
      signer: finalTransfer.ledger,
      public_key: finalTransferState.public_key,
      type: finalTransferState.type
    }))
}```

I don't think the function above is easily useable by RC as there are assumptions on the structure of `finalTransfer`. This function could be broken in two I think.

**Comment by MatthewPhinney** [comment]
OK, let me update, and we can sync up on Monday.

**Comment by emschwartz** [comment]
@mwshortt that's already supported by the sender. See [here](https://github.com/interledger/five-bells-sender/blob/master/src/index.js#L84-L85), you can just pass in the `receiptCondition` and it won't use the `getReceiptCondition` function

**Comment by mwshortt** [comment]
@emschwartz I know, but we don't want RC to have to generate the receipt condition itself. We want it to be able to abstract the knowledge of the format of the receipt condition to Five Bells Sender and just pass in the relevant arguments to an exposed function.

**Comment by justmoon** [comment]
The receipt condition depends on the use case. It's something that should be generated by the recipient. The recipient in this case is Ripple Connect.

More to the point, there already *is* a module whose job it is to help you generate different conditions really easily: `five-bells-condition`

Here is the code to generate a condition using the [next-generation](https://github.com/interledger/five-bells-condition/tree/feature/binary-merkle-v2) crypto-conditions:

``` js
const myFulfillment = new condition.Sha256Fulfillment()
myFulfillment.setPreimage(new Buffer('[secret random number]'))
console.log(myFulfillment.getCondition().serializeUri())
```

And to generate the corresponding fulfillment:

``` js
const myFulfillment = new condition.Sha256Fulfillment()
myFulfillment.setPreimage(new Buffer('[secret random number]'))
console.log(myFulfillment.serializeUri())
```

(Difference is in the last line. API is still subject to change before the final release.)

So eventually you shouldn't have to keep a lot of complex logic about conditions in Ripple Connect. `five-bells-condition` should do all of the heavy lifting. The only thing that needs to be in Ripple Connect is the use-case specific information about the condition which can be very minimal like the example above. And we can make it even simpler by adding some shortcut functions.

I'll try to have a beta version of the next-gen conditions ready by Monday.

**Comment by MatthewPhinney** [comment]
OK, sounds like there is still some discussion to be had on how we want to handle this. Maybe we can sync up today to sketch out the API and determine where we want to place this logic. @geertweening may have some input, as well.

**Comment by mwshortt** [comment]
lgtm! Thank you!

**Pull request merged**
