### PR TITLE
change "notaries" field in case to an array of URIs

### PR DESCRIPTION
**Pull request by clark800**
Needed for https://github.com/interledger/five-bells-notary/pull/40

### CODE REVIEW

**Comment by MatthewPhinney** [comment]
LGTM

**Comment by emschwartz** [comment]
Are we supporting multiple notaries now? If not, might want to throw an error if you pass in more than one

**Comment by clark800** [comment]
@emschwartz Where would that check be?

**Comment by emschwartz** [comment]
Oh my mistake, I thought you were changing the sender API to allow the user to supply an array

**Comment by clark800** [comment]
I was gonna wait until https://github.com/interledger/five-bells-notary/pull/41 was reviewed before merging this since it depends on it

**Pull request merged**
