### PR TITLE
[FIX] State is 'rejected' not 'cancelled'

### PR DESCRIPTION
**Pull request by MatthewPhinney**

### CODE REVIEW

**Comment by MatthewPhinney** [comment]
cc @nguyenripple @sentientwaffle

**Comment by sentientwaffle** [comment]
It should still be called a 'cancellation condition'.

**Comment by MatthewPhinney** [comment]
> It should still be called a 'cancellation condition'.

Which part of the code are you referring to? It's still called `cancellationCondition` in the params, so I haven't changed the external API.

**Comment by sentientwaffle** [comment]
`getRejectionCondition`, etc. The only part that should change is `s/'cancelled'/'rejected'`.

**Comment by sentientwaffle** [comment]
LGTM

**Pull request merged**
